## open3d 0.9.0

In [1]:
import open3d as o3d
import numpy as np

In [2]:
help(o3d)

Help on package open3d:

NAME
    open3d

DESCRIPTION
    # ----------------------------------------------------------------------------
    # -                        Open3D: www.open3d.org                            -
    # ----------------------------------------------------------------------------
    # The MIT License (MIT)
    #
    # Copyright (c) 2018 www.open3d.org
    #
    # Permission is hereby granted, free of charge, to any person obtaining a copy
    # of this software and associated documentation files (the "Software"), to deal
    # in the Software without restriction, including without limitation the rights
    # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    # copies of the Software, and to permit persons to whom the Software is
    # furnished to do so, subject to the following conditions:
    #
    # The above copyright notice and this permission notice shall be included in
    # all copies or substantial portions of the Software.
   

### IO

In [3]:
help(o3d.io.read_point_cloud)

Help on built-in function read_point_cloud in module open3d.open3d.io:

read_point_cloud(...) method of builtins.PyCapsule instance
    read_point_cloud(filename, format='auto', remove_nan_points=True, remove_infinite_points=True, print_progress=False)
    
    Function to read PointCloud from file
    
    Args:
        filename (str): Path to file.
        format (str, optional, default='auto'): The format of the input file. When not specified or set as ``auto``, the format is inferred from file extension name.
        remove_nan_points (bool, optional, default=True): If true, all points that include a NaN are removed from the PointCloud.
        remove_infinite_points (bool, optional, default=True): If true, all points that include an infinite value are removed from the PointCloud.
        print_progress (bool, optional, default=False): If set to true a progress bar is visualized in the console
    
    Returns:
        open3d.geometry.PointCloud



In [2]:
pcd = o3d.io.read_point_cloud("./data/cloud.pcd")
pcd_with_nan_points = o3d.io.read_point_cloud("./data/cloud.pcd", remove_nan_points=False)
pcd_with_infinite_points = o3d.io.read_point_cloud("./data/cloud.pcd", remove_infinite_points=False)

In [6]:
o3d.visualization.draw_geometries([pcd_with_nan_points])

In [25]:
np.array(pcd.points).size

609894

In [5]:
print(pcd)
print(pcd_with_nan_points)
print(pcd_with_infinite_points)

print(type(pcd))

geometry::PointCloud with 203298 points.
geometry::PointCloud with 307200 points.
geometry::PointCloud with 203298 points.
<class 'open3d.open3d.geometry.PointCloud'>


In [74]:
o3d.io.write_point_cloud("./data/cloud_out.pcd", pcd)

True

In [4]:
model = o3d.io.read_triangle_mesh("./data/model.stl")
print(model)
print(type(model))

geometry::TriangleMesh with 12060 points and 4020 triangles.
<class 'open3d.open3d.geometry.TriangleMesh'>


### PointCloud

In [19]:
help(o3d.open3d.geometry.PointCloud)

Help on class PointCloud in module open3d.open3d.geometry:

class PointCloud(Geometry3D)
 |  PointCloud class. A point cloud consists of point coordinates, and optionally point colors and point normals.
 |  
 |  Method resolution order:
 |      PointCloud
 |      Geometry3D
 |      Geometry
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __add__(...)
 |      __add__(self: open3d.open3d.geometry.PointCloud, arg0: open3d.open3d.geometry.PointCloud) -> open3d.open3d.geometry.PointCloud
 |  
 |  __copy__(...)
 |      __copy__(self: open3d.open3d.geometry.PointCloud) -> open3d.open3d.geometry.PointCloud
 |  
 |  __deepcopy__(...)
 |      __deepcopy__(self: open3d.open3d.geometry.PointCloud, arg0: dict) -> open3d.open3d.geometry.PointCloud
 |  
 |  __iadd__(...)
 |      __iadd__(self: open3d.open3d.geometry.PointCloud, arg0: open3d.open3d.geometry.PointCloud) -> open3d.open3d.geometry.PointCloud
 |  
 |  __init__(...)
 |      __init__

In [21]:
 print(np.asarray(pcd.points))

[[-2.7893591  -2.1468387   5.1780005 ]
 [-1.5618024  -1.24175     2.9950001 ]
 [-3.150022   -2.5900543   6.2470002 ]
 ...
 [ 2.6541948   2.3671136   5.7660003 ]
 [ 3.9989414   3.4377751   8.3740005 ]
 [ 0.28549352  0.22291757  0.54300004]]


In [22]:
print(np.asarray(pcd.colors))

[[0.54117647 0.6        0.56862745]
 [0.14509804 0.15294118 0.1372549 ]
 [0.10588235 0.11372549 0.10980392]
 ...
 [0.26666667 0.25882353 0.12941176]
 [0.23529412 0.24313725 0.22352941]
 [0.29019608 0.3372549  0.30196078]]


### transform

In [84]:
help(pcd.transform)

Help on method transform in module open3d.open3d.geometry:

transform(...) method of open3d.open3d.geometry.PointCloud instance
    transform(self, arg0)
    
    Apply transformation (4x4 matrix) to the geometry coordinates.
    
    Args:
        arg0 (numpy.ndarray[float64[4, 4]])
    
    Returns:
        open3d.geometry.Geometry3D



In [83]:
import copy
pcd_tf = copy.deepcopy(pcd)
pcd_tf.transform([[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]])

o3d.visualization.draw_geometries([pcd])
o3d.visualization.draw_geometries([pcd_tf])

### voxel grid downsample

In [75]:
help(pcd.voxel_down_sample)

Help on method voxel_down_sample in module open3d.open3d.geometry:

voxel_down_sample(...) method of open3d.open3d.geometry.PointCloud instance
    voxel_down_sample(self, voxel_size)
    
    Function to downsample input pointcloud into output pointcloud with a voxel
    
    Args:
        voxel_size (float): Voxel size to downsample into.
    
    Returns:
        open3d.geometry.PointCloud



In [88]:
voxel_down_pcd = pcd.voxel_down_sample(voxel_size=0.05)
print(voxel_down_pcd)

geometry::PointCloud with 10917 points.


In [89]:
o3d.visualization.draw_geometries([pcd], window_name='pcd')
o3d.visualization.draw_geometries([voxel_down_pcd])

### uniform downsample

In [87]:
help(pcd.uniform_down_sample)

Help on method uniform_down_sample in module open3d.open3d.geometry:

uniform_down_sample(...) method of open3d.open3d.geometry.PointCloud instance
    uniform_down_sample(self, every_k_points)
    
    Function to downsample input pointcloud into output pointcloud uniformly. The sample is performed in the order of the points with the 0-th point always chosen, not at random.
    
    Args:
        every_k_points (int): Sample rate, the selected point indices are [0, k, 2k, ...]
    
    Returns:
        open3d.geometry.PointCloud



In [90]:
uni_down_pcd = pcd.uniform_down_sample(every_k_points=5)
print(uni_down_pcd)

geometry::PointCloud with 40660 points.


In [106]:
o3d.visualization.draw_geometries([pcd], window_name='pcd')
o3d.visualization.draw_geometries([uni_down_pcd])

### statistical outlier removal

In [85]:
help(pcd.remove_statistical_outlier)

Help on method remove_statistical_outlier in module open3d.open3d.geometry:

remove_statistical_outlier(...) method of open3d.open3d.geometry.PointCloud instance
    remove_statistical_outlier(self, nb_neighbors, std_ratio)
    
    Function to remove points that are further away from their neighbors in average
    
    Args:
        nb_neighbors (int): Number of neighbors around the target point.
        std_ratio (float): Standard deviation ratio.
    
    Returns:
        Tuple[open3d.geometry.PointCloud, List[int]]



In [101]:
cl, ind = voxel_down_pcd.remove_statistical_outlier(nb_neighbors=20, std_ratio=2.0)
print(cl)
print(len(ind))

geometry::PointCloud with 10808 points.
10808


### select cloud by index

In [100]:
help(voxel_down_pcd.select_down_sample)

Help on method select_down_sample in module open3d.open3d.geometry:

select_down_sample(...) method of open3d.open3d.geometry.PointCloud instance
    select_down_sample(self, indices, invert=False)
    
    Function to select points from input pointcloud into output pointcloud. ``indices``: Indices of points to be selected. ``invert``: Set to ``True`` to invert the selection of indices.
    
    Args:
        indices (List[int]): Indices of points to be selected.
        invert (bool, optional, default=False): Set to ``True`` to invert the selection of indices.
    
    Returns:
        open3d.geometry.PointCloud



In [102]:
print(voxel_down_pcd)

inlier_cloud = voxel_down_pcd.select_down_sample(ind)
print(inlier_cloud)

outlier_cloud = voxel_down_pcd.select_down_sample(ind, invert=True)
print(outlier_cloud)

print("Showing outliers (red) and inliers (gray): ")
outlier_cloud.paint_uniform_color([1, 0, 0])
inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])
o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud])

geometry::PointCloud with 10917 points.
geometry::PointCloud with 10808 points.
geometry::PointCloud with 109 points.
Showing outliers (red) and inliers (gray): 


### radius outlier removal

In [86]:
help(pcd.remove_radius_outlier)

Help on method remove_radius_outlier in module open3d.open3d.geometry:

remove_radius_outlier(...) method of open3d.open3d.geometry.PointCloud instance
    remove_radius_outlier(self, nb_points, radius)
    
    Function to remove points that have less than nb_points in a given sphere of a given radius
    
    Args:
        nb_points (int): Number of points within the radius.
        radius (float): Radius of the sphere.
    
    Returns:
        Tuple[open3d.geometry.PointCloud, List[int]]



In [105]:
cl, ind = voxel_down_pcd.remove_radius_outlier(nb_points=5, radius=0.05)
inlier_cloud = voxel_down_pcd.select_down_sample(ind)
outlier_cloud = voxel_down_pcd.select_down_sample(ind, invert=True)

print(inlier_cloud)
print(outlier_cloud)

print("Showing outliers (red) and inliers (gray): ")
outlier_cloud.paint_uniform_color([1, 0, 0])
inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])
o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud])

geometry::PointCloud with 3306 points.
geometry::PointCloud with 7611 points.
Showing outliers (red) and inliers (gray): 


### pick points in visulization

In [4]:
vis = o3d.visualization.VisualizerWithEditing()

vis.create_window()
vis.add_geometry(pcd)
vis.run()
vis.destroy_window()

aa = vis.get_picked_points()
print(aa)

[134116]


In [5]:
print(pcd.points[aa[0]])

[-0.03773436  0.28421903  3.8090003 ]


### Crop

In [111]:
help(pcd.crop)

Help on method crop in module open3d.open3d.geometry:

crop(...) method of open3d.open3d.geometry.PointCloud instance
    crop(bounding_box, bounding_box)
    
    Function to crop input pointcloud into output pointcloud
    
    Args:
        bounding_box (open3d.geometry.AxisAlignedBoundingBox) ): AxisAlignedBoundingBox to crop points
        bounding_box (open3d.geometry.OrientedBoundingBox): AxisAlignedBoundingBox to crop points
    
    Returns:
        open3d.geometry.PointCloud



In [113]:
help(o3d.geometry.AxisAlignedBoundingBox)

Help on class AxisAlignedBoundingBox in module open3d.open3d.geometry:

class AxisAlignedBoundingBox(Geometry3D)
 |  Class that defines an axis_aligned box that can be computed from 3D geometries, The axis aligned bounding box uses the cooridnate axes for bounding box generation.
 |  
 |  Method resolution order:
 |      AxisAlignedBoundingBox
 |      Geometry3D
 |      Geometry
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __copy__(...)
 |      __copy__(self: open3d.open3d.geometry.AxisAlignedBoundingBox) -> open3d.open3d.geometry.AxisAlignedBoundingBox
 |  
 |  __deepcopy__(...)
 |      __deepcopy__(self: open3d.open3d.geometry.AxisAlignedBoundingBox, arg0: dict) -> open3d.open3d.geometry.AxisAlignedBoundingBox
 |  
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. __init__(self: open3d.open3d.geometry.AxisAlignedBoundingBox) -> None
 |      
 |      Default constructor
 |  

In [8]:

center_point = np.array(pcd.points[aa[0]])
min_bound = center_point - np.asarray([1, 0.3, 0.3])
max_bound = center_point + np.asarray([1, 0.3, 0.3])

cropbox = o3d.geometry.AxisAlignedBoundingBox(min_bound=min_bound, max_bound=max_bound)
cloud_cropped = pcd.crop(cropbox)
print(cloud_cropped)

cloud_cropped.paint_uniform_color([1, 0, 0])
o3d.visualization.draw_geometries([pcd, cloud_cropped])

geometry::PointCloud with 10312 points.


In [25]:
lines_set = o3d.geometry.LineSet.create_from_axis_aligned_bounding_box(cropbox)
lines_set.paint_uniform_color([0,1,0])

o3d.visualization.draw_geometries([cloud_cropped, pcd, lines_set])

In [2]:
help(o3d.geometry.OrientedBoundingBox)

Help on class OrientedBoundingBox in module open3d.open3d.geometry:

class OrientedBoundingBox(Geometry3D)
 |  Class that defines an oriented box that can be computed from 3D geometries.
 |  
 |  Method resolution order:
 |      OrientedBoundingBox
 |      Geometry3D
 |      Geometry
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __copy__(...)
 |      __copy__(self: open3d.open3d.geometry.OrientedBoundingBox) -> open3d.open3d.geometry.OrientedBoundingBox
 |  
 |  __deepcopy__(...)
 |      __deepcopy__(self: open3d.open3d.geometry.OrientedBoundingBox, arg0: dict) -> open3d.open3d.geometry.OrientedBoundingBox
 |  
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. __init__(self: open3d.open3d.geometry.OrientedBoundingBox) -> None
 |      
 |      Default constructor
 |      
 |      2. __init__(self: open3d.open3d.geometry.OrientedBoundingBox, arg0: open3d.open3d.geometry.Oriented

### estimate normals

In [40]:
help(downpcd.estimate_normals)

Help on method estimate_normals in module open3d.open3d.geometry:

estimate_normals(...) method of open3d.open3d.geometry.PointCloud instance
    estimate_normals(self, search_param=geometry::KDTreeSearchParamKNN with knn = 30, fast_normal_computation=True)
    
    Function to compute the normals of a point cloud. Normals are oriented with respect to the input point cloud if normals exist
    
    Args:
        search_param (open3d.geometry.KDTreeSearchParam, optional, default=geometry::KDTreeSearchParamKNN with knn = 30): The KDTree search parameters for neighborhood search.
        fast_normal_computation (bool, optional, default=True): If true, the normal estiamtion uses a non-iterative method to extract the eigenvector from the covariance matrix. This is faster, but is not as numerical stable.
    
    Returns:
        bool



In [42]:
downpcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(
    radius=0.1, max_nn=30))
print("Print a normal vector of the 0th point")
print(downpcd.normals[0])
print("Print the normal vectors of 10 points")
print(np.asarray(downpcd.normals)[100:110, :])

Print a normal vector of the 0th point
[0. 0. 1.]
Print the normal vectors of 10 points
[[ 0.16563201 -0.44525358 -0.87995187]
 [ 0.33267926 -0.66822808 -0.66542899]
 [ 0.33891198  0.44516458  0.82883482]
 [ 0.5504408   0.34147279 -0.76184727]
 [ 0.97976639 -0.19808279  0.02865362]
 [ 0.99523413  0.02386782  0.09454813]
 [ 0.99532676  0.02746002  0.09257745]
 [-0.22503048  0.61875917  0.75266086]
 [-0.31581652 -0.05706292  0.94710282]
 [ 0.66643013  0.63739875 -0.38677346]]


### segment plane

In [12]:
help(pcd.segment_plane)

Help on method segment_plane in module open3d.open3d.geometry:

segment_plane(...) method of open3d.open3d.geometry.PointCloud instance
    segment_plane(self, distance_threshold, ransac_n, num_iterations)
    
    Segments a plane in the point cloud using the RANSAC algorithm.
    
    Args:
        distance_threshold (float): Max distance a point can be from the plane model, and still be considered an inlier.
        ransac_n (int): Number of initial points to be considered inliers in each iteration.
        num_iterations (int): Number of iterations.
    
    Returns:
        Tuple[numpy.ndarray[float64[4, 1]], List[int]]



In [109]:
plane_model, inliers = pcd.segment_plane(distance_threshold=0.01,
                                         ransac_n=3,
                                         num_iterations=1000)

print(plane_model)

[a, b, c, d] = plane_model
print(f"Plane equation: {a:.2f}x + {b:.2f}y + {c:.2f}z + {d:.2f} = 0")

[-0.04532055  0.53486659  0.8437202   3.3474089 ]
Plane equation: -0.05x + 0.53y + 0.84z + 3.35 = 0


In [154]:
inlier_cloud = pcd.select_down_sample(inliers)
inlier_cloud.paint_uniform_color([1, 0, 0])
o3d.visualization.draw_geometries([pcd, inlier_cloud])